name: Vercel Preview Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  pull_request:
    branches:
      - '**' # Trigger on all PRs

jobs:
  vercel-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest pnpm

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=preview 

      - name: Build Project
        run: NEXT_PUBLIC_VERCEL_ENV=preview vercel build

      - name: Deploy Preview to Vercel
        id: vercel_deploy
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --confirm)
          echo "preview_url=$url" >> $GITHUB_OUTPUT

      - name: Comment Preview URL on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vercel-preview
          message: |
            🚀 Vercel Preview Deployment Ready!
            🔗 [View Preview Deployment](${{ steps.vercel_deploy.outputs.preview_url }})
